type: AppearanceValidation
data_preprocessor:
  type: WildLifeReIDPreprocessor
re_identificator:
  metainfo: ../tests/configs/re-identification_metadata.yaml
  checkpoint: ../tests/configs/precision_track_re-identificator.onnx
validated_classes: ["mouse"]
min_consecutive_hits: 5
