dataset_info = dict(
    dataset_name="ap10k",
    paper_info=dict(
        author="Yu, Hang and Xu, Yufei and Zhang, Jing and " "Zhao, Wei and Guan, Ziyu and Tao, Dacheng",
        title="AP-10K: A Benchmark for Animal Pose Estimation in the Wild",
        container="35th Conference on Neural Information Processing Systems " "(NeurIPS 2021) Track on Datasets and Bench-marks.",
        year="2021",
        homepage="https://github.com/AlexTheBad/AP-10K",
    ),
    keypoint_info=[
        dict(name="Left Eye", swap="Right Eye"),
        dict(name="Right Eye", swap="Left Eye"),
        dict(name="Nose", swap=""),
        dict(name="Neck", swap=""),
        dict(name="Root of tail", swap=""),
        dict(name="Left Shoulder", swap="Right Shoulder"),
        dict(name="Left Elbow", swap="Right Elbow"),
        dict(name="Left Front Paw", swap="Right Front Paw"),
        dict(name="Right Shoulder", swap="Left Shoulder"),
        dict(name="Right Elbow", swap="Left Elbow"),
        dict(name="Right Front Paw", swap="Left Front Paw"),
        dict(name="Left Hip", swap="Right Hip"),
        dict(name="Left Knee", swap="Right Knee"),
        dict(name="Left Back Paw", swap="Right Back Paw"),
        dict(name="Right Hip", swap="Left Hip"),
        dict(name="Right Knee", swap="Left Knee"),
        dict(name="Right Back Paw", swap="Left Back Paw"),
    ],
    skeleton_info=[
        dict(link=("Left Eye", "Right Eye")),
        dict(link=("Left Eye", "Nose")),
        dict(link=("Right Eye", "Nose")),
        dict(link=("Nose", "Neck")),
        dict(link=("Neck", "Root of tail")),
        dict(link=("Neck", "Left Shoulder")),
        dict(link=("Left Shoulder", "Left Elbow")),
        dict(link=("Left Elbow", "Left Front Paw")),
        dict(link=("Neck", "Right Shoulder")),
        dict(link=("Right Shoulder", "Right Elbow")),
        dict(link=("Right Elbow", "Right Front Paw")),
        dict(link=("Root of tail", "Left Hip")),
        dict(link=("Left Hip", "Left Knee")),
        dict(link=("Left Knee", "Left Back Paw")),
        dict(link=("Root of tail", "Right Hip")),
        dict(link=("Right Hip", "Right Knee")),
        dict(link=("Right Knee", "Right Back Paw")),
    ],
    joint_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5],
    sigmas=[0.025, 0.025, 0.026, 0.035, 0.035, 0.079, 0.072, 0.062, 0.079, 0.072, 0.062, 0.107, 0.087, 0.089, 0.107, 0.087, 0.089],
    classes=[
        "antelope",
        "buffalo",
        "cow",
        "sheep",
        "dog",
        "fox",
        "wolf",
        "monkey",
        "noisy night monkey",
        "spider monkey",
        "deer",
        "elephant",
        "horse",
        "zebra",
        "cat",
        "cheetah",
        "lion",
        "tiger",
        "giraffe",
        "hippo",
        "chimpanzee",
        "gorilla",
        "orangutan",
        "rabbit",
        "raccoon",
        "rhino",
        "pig",
        "black bear",
        "panda",
        "polar bear",
    ],
)
