dataset_info = dict(
    dataset_name="coco",
    paper_info=dict(
        author="Lin, Tsung-Yi and Maire, Michael and "
        "Belongie, Serge and Hays, James and "
        "Perona, Pietro and Ramanan, Deva and "
        r"Doll{\'a}r, Piotr and Zitnick, C Lawrence",
        title="Microsoft coco: Common objects in context",
        container="European conference on computer vision",
        year="2014",
        homepage="http://cocodataset.org/",
    ),
    keypoint_info={
        0: dict(name="nose", id=0, type="upper", swap=""),
        1: dict(name="left_eye", id=1, type="upper", swap="right_eye"),
        2: dict(name="right_eye", id=2, type="upper", swap="left_eye"),
        3: dict(name="left_ear", id=3, type="upper", swap="right_ear"),
        4: dict(name="right_ear", id=4, type="upper", swap="left_ear"),
        5: dict(name="left_shoulder", id=5, type="upper", swap="right_shoulder"),
        6: dict(name="right_shoulder", id=6, type="upper", swap="left_shoulder"),
        7: dict(name="left_elbow", id=7, type="upper", swap="right_elbow"),
        8: dict(name="right_elbow", id=8, type="upper", swap="left_elbow"),
        9: dict(name="left_wrist", id=9, type="upper", swap="right_wrist"),
        10: dict(name="right_wrist", id=10, type="upper", swap="left_wrist"),
        11: dict(name="left_hip", id=11, type="lower", swap="right_hip"),
        12: dict(name="right_hip", id=12, type="lower", swap="left_hip"),
        13: dict(name="left_knee", id=13, type="lower", swap="right_knee"),
        14: dict(name="right_knee", id=14, type="lower", swap="left_knee"),
        15: dict(name="left_ankle", id=15, type="lower", swap="right_ankle"),
        16: dict(name="right_ankle", id=16, type="lower", swap="left_ankle"),
    },
    skeleton_info={
        0: dict(link=("left_ankle", "left_knee"), id=0),
        1: dict(link=("left_knee", "left_hip"), id=1),
        2: dict(link=("right_ankle", "right_knee"), id=2),
        3: dict(link=("right_knee", "right_hip"), id=3),
        4: dict(link=("left_hip", "right_hip"), id=4),
        5: dict(link=("left_shoulder", "left_hip"), id=5),
        6: dict(link=("right_shoulder", "right_hip"), id=6),
        7: dict(link=("left_shoulder", "right_shoulder"), id=7),
        8: dict(link=("left_shoulder", "left_elbow"), id=8),
        9: dict(link=("right_shoulder", "right_elbow"), id=9),
        10: dict(link=("left_elbow", "left_wrist"), id=10),
        11: dict(link=("right_elbow", "right_wrist"), id=11),
        12: dict(link=("left_eye", "right_eye"), id=12),
        13: dict(link=("nose", "left_eye"), id=13),
        14: dict(link=("nose", "right_eye"), id=14),
        15: dict(link=("left_eye", "left_ear"), id=15),
        16: dict(link=("right_eye", "right_ear"), id=16),
        17: dict(link=("left_ear", "left_shoulder"), id=17),
        18: dict(link=("right_ear", "right_shoulder"), id=18),
    },
    joint_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5],
    sigmas=[0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062, 0.107, 0.107, 0.087, 0.087, 0.089, 0.089],
    classes=["Human"],
)
