dataset_info = dict(
    dataset_name="coco",
    paper_info=dict(
        author="Lin, Tsung-Yi and Maire, Michael and "
        "Belongie, Serge and Hays, James and "
        "Perona, Pietro and Ramanan, Deva and "
        r"Doll{\'a}r, Piotr and Zitnick, C Lawrence",
        title="Microsoft coco: Common objects in context",
        container="European conference on computer vision",
        year="2014",
        homepage="http://cocodataset.org/",
    ),
    keypoint_info=[
        dict(name="nose", swap=""),
        dict(name="left_eye", swap="right_eye"),
        dict(name="right_eye", swap="left_eye"),
        dict(name="left_ear", swap="right_ear"),
        dict(name="right_ear", swap="left_ear"),
        dict(name="left_shoulder", swap="right_shoulder"),
        dict(name="right_shoulder", swap="left_shoulder"),
        dict(name="left_elbow", swap="right_elbow"),
        dict(name="right_elbow", swap="left_elbow"),
        dict(name="left_wrist", swap="right_wrist"),
        dict(name="right_wrist", swap="left_wrist"),
        dict(name="left_hip", swap="right_hip"),
        dict(name="right_hip", swap="left_hip"),
        dict(name="left_knee", swap="right_knee"),
        dict(name="right_knee", swap="left_knee"),
        dict(name="left_ankle", swap="right_ankle"),
        dict(name="right_ankle", swap="left_ankle"),
    ],
    skeleton_info=[
        dict(link=("left_ankle", "left_knee")),
        dict(link=("left_knee", "left_hip")),
        dict(link=("right_ankle", "right_knee")),
        dict(link=("right_knee", "right_hip")),
        dict(link=("left_hip", "right_hip")),
        dict(link=("left_shoulder", "left_hip")),
        dict(link=("right_shoulder", "right_hip")),
        dict(link=("left_shoulder", "right_shoulder")),
        dict(link=("left_shoulder", "left_elbow")),
        dict(link=("right_shoulder", "right_elbow")),
        dict(link=("left_elbow", "left_wrist")),
        dict(link=("right_elbow", "right_wrist")),
        dict(link=("left_eye", "right_eye")),
        dict(link=("nose", "left_eye")),
        dict(link=("nose", "right_eye")),
        dict(link=("left_eye", "left_ear")),
        dict(link=("right_eye", "right_ear")),
        dict(link=("left_ear", "left_shoulder")),
        dict(link=("right_ear", "right_shoulder")),
    ],
    joint_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5, 1.0, 1.0, 1.2, 1.2, 1.5, 1.5],
    sigmas=[0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062, 0.107, 0.107, 0.087, 0.087, 0.089, 0.089],
    classes=["Human"],
)
