dataset_info = dict(
    dataset_name="",
    paper_info=dict(),
    keypoint_info=[
        dict(name="Nose", swap=""),
        dict(name="Head", swap=""),
        dict(name="Left Ear", swap="Right Ear"),
        dict(name="Right Ear", swap="Left Ear"),
        dict(name="UpperBack", swap=""),
        dict(name="Back", swap=""),
        dict(name="LowerBack", swap=""),
        dict(name="Tailbase", swap=""),
        dict(name="Left Shoulder", swap="Right Shoulder"),
        dict(name="Right Shoulder", swap="Left Shoulder"),
        dict(name="Right Hip", swap="Left Hip"),
        dict(name="Left Hip", swap="Right Hip"),
    ],
    skeleton_info=[
        dict(link=("Nose", "Head")),
        dict(link=("Head", "Left Ear")),
        dict(link=("Head", "Right Ear")),
        dict(link=("Head", "UpperBack")),
        dict(link=("UpperBack", "Back")),
        dict(link=("UpperBack", "Left Shoulder")),
        dict(link=("UpperBack", "Right Shoulder")),
        dict(link=("Back", "LowerBack")),
        dict(link=("LowerBack", "Left Hip")),
        dict(link=("LowerBack", "Right Hip")),
        dict(link=("LowerBack", "Tailbase")),
    ],
    joint_weights=[1] * 12,
    sigmas=[0.1] * 12,
    classes=["mouse"],
    actions=[
        "Other",
        "Running",
        "Interacting",
        "Rearing",
        "Grooming",
    ],
)
