# ================================
# General on/off options
# ================================
booleans:
  pipelined: true
  with_validation: false
  with_action_recognition: false
  with_group_action_recognition: false
  with_pose_estimation: true

# ================================
# General directories and paths
# ================================
general:
  metainfo: "../configs/metadata/mice.py"

# ================================
# Training parameters, directories and paths
# ================================
training:
  dataset_name: "mice"

  data_root: "../../datasets/MICE/pose-estimation/"

  resume: false
  training_checkpoint: "../checkpoints/model_ap/model_ap.pth"

  deploying_directory: "../checkpoints/mice/"
  deploying_sanity_check_img_path: "images/0000003435.jpg"

  batch_size: 38 # Warning: The training is unstable with batch sizes < 16.
  wandb_logging: false

# ================================
# Tracking parameters, directories and paths
# ================================
tracking:
  saving_directory: "../work_dir/"
  num_subjects: { "mouse": 20 }
  tracking_checkpoint_name: "model_mice_DEPLOYED.pth"
  mot_data_root: "../../datasets/MICE/pose-estimation/benchmark/"

# ================================
# Action Recognition parameters
# ================================
action_recognition:
  mart_checkpoint_name: "mart_DEPLOYED.pth"
  action_recognition_data_root: "../../datasets/MICE/sequential/"

# ================================
# Group Action Recognition parameters
# ================================
group_action_recognition:
  gmart_checkpoint_name: "gmart_DEPLOYED.pth"

# ================================
# Validation parameters
# ================================
validation:
  validation_configuration_file: "../configs/settings/validation/appearance.yaml"

# ================================
# Visualization parameters
# ================================
visualization:
  display_bounding_boxes: false
  display_poses: true
  display_velocities: true
  display_species: true
  display_confidence_scores: true
  display_actions: false
  display_search_zones: false
  display_validations: false
  display_untracked_detections: false
  display_predicted_bounding_boxes: false
