# ================================
# General on/off options
# ================================
booleans:
  pipelined: false
  with_validation: false
  with_action_recognition: true
  with_group_action_recognition: true
  with_pose_estimation: true

# ================================
# General directories and paths
# ================================
general:
  metainfo: "../configs/metadata/mice.py"
  # metainfo: "../../datasets/zebrafish/zebrafish.py"
  # metainfo: "../../datasets/stripedmice/stripedmice_corrected_without_tail.py"

# ================================
# Training parameters, directories and paths
# ================================
training:
  dataset_name: "mice"

  data_root: "../../datasets/MICE/pose-estimation/"

  resume: false
  training_checkpoint: "../checkpoints/model_ap/model_ap.pth"

  deploying_directory: "../checkpoints/mice/"

  # deploying_directory: "../checkpoints/zebrafish/"
  # deploying_directory: "../checkpoints/camille/"

  deploying_sanity_check_img_path: "images/0000003435.jpg"

  batch_size: 38 # Warning: The training is unstable with batch sizes < 16.
  wandb_logging: false

# ================================
# Tracking parameters, directories and paths
# ================================
tracking:
  saving_directory: "../work_dir/"
  num_subjects: { "mouse": 20 }
  # num_subjects: { "zebrafish": -1 }

  # tracking_checkpoint_name: "zebrafish.pth"
  tracking_checkpoint_name: "model_mice_DEPLOYED.pth"
  # tracking_checkpoint_name: "model_camille_DEPLOYED.onnx"
  mot_testing_data_root: "../../datasets/MICE/pose-estimation/benchmark/"

# ================================
# Validation parameters
# ================================
validation:
  validation_configuration_file: "../configs/settings/validation/appearance.yaml"

# ================================
# Visualization parameters
# ================================
visualization:
  display_bounding_boxes: false
  display_poses: true
  display_velocities: false
  display_species: false
  display_confidence_scores: false
  display_actions: true
  display_search_zones: false
  display_validations: false
  display_untracked_detections: false
  display_predicted_bounding_boxes: false
