name: Formating

on: [push, pull_request]

jobs:
  format:
    name: Run Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black docformatter isort mdformat

      - name: Run Black
        run: black .

      # - name: Run Docformatter
      #   run: docformatter --in-place --recursive .

      - name: Run Isort
        run: isort .

      - name: Run Mdformat
        run: mdformat .

      # - name: Commit and push changes
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git add .
      #     git commit -m "Format code and documents with Black, Docformatter, Isort, and Mdformat"
      #     git push "https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
